language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t training/docker-react -f Dockerfile.dev .

#Commands to run when test suite is executed
script:
  - docker run -e CI=true training/docker-react npm run test

#Tell travis how to deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-341321452573"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: "$AWS_ACCESS_KEY"
secret_access_key: "$AWS_SECRET_KEY"